// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_assignment/test/lib/features/users/data/repositories/repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_assignment/core/network/network_info.dart' as _i6;
import 'package:flutter_assignment/features/users/data/datasource/local_datasource.dart'
    as _i5;
import 'package:flutter_assignment/features/users/data/datasource/remote_datasource.dart'
    as _i2;
import 'package:flutter_assignment/features/users/data/models/user_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDatasource extends _i1.Mock implements _i2.RemoteDatasource {
  MockRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserModel>> fetchUser(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUser, [page]),
            returnValue: _i3.Future<List<_i4.UserModel>>.value(
              <_i4.UserModel>[],
            ),
          )
          as _i3.Future<List<_i4.UserModel>>);
}

/// A class which mocks [LocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDatasource extends _i1.Mock implements _i5.LocalDatasource {
  MockLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheUsers(List<_i4.UserModel>? users, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUsers, [users, date]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.UserModel>> getCachedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUsers, []),
            returnValue: _i3.Future<List<_i4.UserModel>>.value(
              <_i4.UserModel>[],
            ),
          )
          as _i3.Future<List<_i4.UserModel>>);
}

/// A class which mocks [NetworkConnectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkConnectivity extends _i1.Mock
    implements _i6.NetworkConnectivity {
  MockNetworkConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
